repos:
-   repo: https://github.com/pycqa/isort
    rev: 5.5.2
    hooks:
    - id: isort
      files: 'app/.*'
    - id: isort
      files: 'tests/.*'
-   repo: https://github.com/psf/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.10
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
    - id: flake8
